### PR TITLE
Update clap

### PR DESCRIPTION
**Pull request by r-ml**
Update clap dependency from v3.0.0-beta.2 to v3.0.0-beta.4.

There are [breaking changes](https://github.com/clap-rs/clap/blob/v3.0.0-beta.4/CHANGELOG.md#breaking-changes-1) in the latest clap release that break `rust-script`'s installation, as `cargo`'s dependency resolver assumes that `beta.2` and `beta.4` are compatible. The result of this is `cargo install rust-script` fails with multiple 
```
no method named `multiple` found for struct `Arg` in the current scope
```

To verify this, just clone the repository and run `cargo update`. You'll see that `cargo` updates `clap` and running `cargo build` fails with the error above.

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks!

**Comment by fornwall** [comment]
Seems some issues were introduced by the clap upgrade - https://github.com/fornwall/rust-script/commit/32ac67f6f8fbeb575336da52f609605298e4619d should fix these, let me know if you spot issues with that!

**Comment by r-ml** [comment]
> Seems some issues were introduced by the clap upgrade - [32ac67f](https://github.com/fornwall/rust-script/commit/32ac67f6f8fbeb575336da52f609605298e4619d) should fix these, let me know if you spot issues with that!

Thanks!, I'm using the scripts with arguments, so `rust-script script.rs arg1` and didn't check the no arguments case. Sorry about that :pray: . I works well now!

**Comment by r-ml** [comment]
I might rely too much on CI, these days :sweat_smile:

**Pull request merged**
